### PR TITLE
Fix. Call `multi` callbacks with correct Lua state

### PR DESCRIPTION
**Pull request by moteus**
Close #78

### CODE REVIEW

**Comment by uudiin** [comment]
It's OK, I have tested already

**Comment by uudiin** [comment]
It will still crash in some case.
It creashed in lcurl_multi_timer_callback with p->L = NULL.

**Comment by moteus** [comment]
Did you can figureout from which curl function it called?

**Comment by uudiin** [comment]
lua_gettop(lua_State * L) 行 118	C
lcurl_multi_timer_callback(void * multi, long ms, void * arg) 行 420	C
update_timer(Curl_multi * multi) 行 2806	C
curl_multi_remove_handle(Curl_multi * multi, Curl_easy * data) 行 780	C
lcurl_multi_info_read(lua_State * L) 行 216	C
...
lua_pcall(lua_State * L, int nargs, int nresults, int errfunc) 行 1052	C
luv_call_callback(lua_State * L, luv_handle_t * data, int id, int nargs) 行 96	C
luv_poll_cb(uv_poll_s * handle, int status, int events) 行 80	C
uv__fast_poll_process_poll_req(uv_loop_s * loop, uv_poll_s * handle, uv_req_s * req) 行 219	C
uv_process_poll_req(uv_loop_s * loop, uv_poll_s * handle, uv_req_s * req) 行 623	C
uv_process_reqs(uv_loop_s * loop) 行 206	C
uv_run(uv_loop_s * loop, uv_run_mode mode) 行 391	C
luv_run(lua_State * L) 行 33	C
...
lua_pcall(lua_State * L, int nargs, int nresults, int errfunc) 行 1052	C
docall(lua_State * L, int narg, int clear) 行 124	C
handle_script(lua_State * L, char * * argv, int n) 行 291	C
pmain(lua_State * L) 行 540	C
...
lua_cpcall(lua_State * L, int(*)(lua_State *) func, void * ud) 行 1074	C
main(int argc, char * * argv) 行 568	C

**Comment by uudiin** [comment]
I use luajit.

**Comment by moteus** [comment]
Please test last commit

**Comment by uudiin** [comment]
It's OK. I have tested already.

**Pull request merged**
