### PR TITLE
Split v2 and v3

### PR DESCRIPTION
**Pull request by cryi**

### CODE REVIEW

**Comment by cryi** [comment]
Hi @moteus, I tried this on linux but I am getting ~20 failed assertions. Same for not modified and modified code. So I assume these changes are ok?

Usually stuff like 
```
 17) Failure (read_stream_callback.test_abort_01):
./test_easy.lua:577: nil expected but was [LcURL Easy (0x55f67b209c98)]

 18) Failure (read_stream_callback.test_pass_01):
./test_easy.lua:625: nil expected but was [LcURL Easy (0x55f67b25aa18)]

 19) Failure (read_stream_callback.test_pause):
./test_easy.lua:655: table expected but was nil
./test_easy.lua:655: 1

 20) Failure (read_stream_callback.test_co_multi):
./test_easy.lua:546: table expected but was nil
./test_easy.lua:546: 1

 21) Failure (read_stream_callback.test_co):
./test_easy.lua:566: table expected but was nil
./test_easy.lua:566: 1

 22) Failure (read_stream_callback.test):
./test_easy.lua:509: table expected but was nil
./test_easy.lua:509: 1
```

I have hard to test on windows. Any chance you could test it?

**Comment by zhaozg** [comment]
Lua code style mismatch

**Comment by cryi** [comment]
~~Hi @zhaozg, yes thats another thing I wanted to discus. The code did not have any indentation so it was hard to back track scopes. So I indented it. Do you want me to match original style?~~

**Comment by cryi** [comment]
Hi, indeed code style was the issue. I matched code style with original cURL.lua and now all test are passing. So we should be ready to merge 🙂

**Comment by cryi** [comment]
And could you release after this PR (`0.3.14`)?

**Comment by cryi** [comment]
We migrated to lua-corehttp. Closing.

**Pull request closed without merging**
