### PR TITLE
implemented support for custom curl_global_init

### LINKED ISSUE #121: Allows do not init libcurl when load lua-curl.
We use some host application which already loads libcurl and calls `curl_global_init`.
After that host application creates Lua state and runs Lua script which  load lua-curl.
In this case we have not call curl_global_init because host application
may configure curl not in default mode.

Real life use case - FreeSWITCH.

I can imagine 2 way.
  1. some environment variable (e.g. `LCURL_NO_INIT`)
  2. separate load function `luaopen_lcurl_no_init`

I prefer first variant.

### PR DESCRIPTION
**Pull request by cryi**
Hi, 

I tried to resolve #121. Everything works as before and I verified that library is not initialized if LCURL_NO_INIT set. Manual initialization is possible with init function on both lcurl and lcurl.safe.  Although I am not sure whether expose CURL_GLOBAL_DEFAULT and others directly on lcurl and lcurls.safe, so for now initialization mode has to be passed as number. 

Although I am not able to verify custom initialization. I use only easy methods and easy calls curl_global_init on its own in case it was not initialized before. It would be great if you can test in more suitable scenario.

Fixes #121.

### CODE REVIEW

**Comment by moteus** [comment]
This is not a solution for #121 
There the main problem that host application init libcurl by itself and then run Lua code.
So in this case Lua should not init curl at all.

**Comment by cryi** [comment]
Are you sure @moteus? Setting it from lua is just optional. As long as `LCURL_NO_INIT` is specified - check [here](https://github.com/Lua-cURL/Lua-cURLv3/pull/169/files#diff-6343160a2cb507b2aa64455a4e9b1ed8cbefd3c5013c1ecd460f77d8feb05287R430). Lua wont initialize libcurl on its own. 

I just added option to initialize it from lua manually on top of your requirement to disable initialization.

**Comment by moteus** [comment]
Sorry. You are right. 
I have only one (very small) concern. getenv is not thread safe function.
But I do not see a better way to handle this rather than just ignoring this.

**Comment by cryi** [comment]
Well curl_global_init is not thread safe on its own. So in context of loading lcurl there should not be difference after merging. 

`getenv` thread safety is mostly about the validity of pointer it returns (it may invalidated over time in multi threaded setup) but we do not care for its validity - we do not read anything from it. 
NULL value is our only concern here and only potential issue I can see, would be if someone tries to set `LCURL_NO_INIT` from background thread while loading lcurl on main or vice versa. We can mention that in docs. 

But I believe that devs working in multithreaded lua realize that initialization has to be done before everything else and as such setting `LCURL_NO_INIT` has to be done before spawning multiple threads of lcurl or lua states containing lcurl.

**Pull request merged**
